### PR TITLE
add #nomad/env-format

### LINKED ISSUE #23: add #nomad/env-format
Very useful to be able to construct strings inside a config file.

```
#nomad/env-format ["http://%s:%s/api/1.0" API_HOST API_PORT]
```

See `#envf` here;

https://github.com/juxt/joplin#hiding-secrets-from-the-configuration-map

### PR DESCRIPTION
**Pull request by martintrojer**
fixes #23

### CODE REVIEW

**Comment by martintrojer** [comment]
@jarohen whatcha think?

**Comment by jarohen** [comment]
Thanks Martin, will get that merged over the weekend :)

**Comment by jarohen** [comment]
On balance, went for `envf` in the end - it's closer to `printf`, `infof`, which people are probably more likely to be familiar with - and there's not a lot in Nomad tying it to `env-format`.

Thanks for the PR, released 0.7.2 :)

James

**Comment by martintrojer** [comment]
woo!

**Pull request merged**
